name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run Docker container
        run: docker run --rm -v "${{ github.workspace }}/logs/:/home/logs/" logger

      - name: Prepare logs directory
        run: |
          mkdir -p logs
          chmod -R 777 logs
          if [ -z "$(ls -A logs)" ]; then
            echo "No logs generated, creating dummy.log" > logs/dummy.log
          fi


      - name: Create dummy log if logs empty
        run: |
          mkdir -p logs
          if [ -z "$(ls -A logs)" ]; then
            echo "No logs generated, creating dummy.log" > logs/dummy.log
          fi

      - name: Check logs directory
        run: ls -R logs/

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
